import CFGclass
import util
import tkinter as Tk
class connection:
    def __init__(self,windows):
        self.mainwin=windows
    def openTBwindow(self):
        TBwin=Tk.Toplevel(self.mainwin)
        TBwin.geometry("800x600")
        Frame=Tk.Frame(TBwin,height=600,width=1000,background="#EDE7E3")
        Frame.place(relx=0.5,rely=0.5,anchor=Tk.CENTER)
        Frame.pack(fill="both",expand=True)
        LsFM=Tk.Frame(Frame,height=600,width=500,background="#EDE7E3")
        LsFM.place(relx=0.5,rely=0.5,anchor=Tk.CENTER)
        LsFM.pack(fill="none",side=Tk.LEFT)
        Combt=Tk.Button(Frame,background="#82C0CC",text="comfirm",width=20,height=2,command=self.getmachine,font=("Arial", 10,"bold"))
        Combt.place(relx=0.5,rely=0.5,anchor=Tk.W)
        Combt.pack(fill="none",expand=True)
        LbT=Tk.Label(LsFM,text="Variable terminal:",font=("Arial", 10),background="#EDE7E3")
        LbT.grid(column=0,row=0)
        self.EtrT=Tk.Entry(LsFM,width=50)
        self.EtrT.grid(column=1,row=0)
        LbV=Tk.Label(LsFM,text="Variable non terminal:",font=("Arial", 10),background="#EDE7E3")
        LbV.grid(column=0,row=1)
        self.EtrV=Tk.Entry(LsFM,width=50)
        self.EtrV.grid(column=1,row=1)
        LbP=Tk.Label(LsFM,text="Produksi yang ada:",font=("Arial", 10),background="#EDE7E3")
        LbP.grid(column=0,row=2)
        self.EtrP=Tk.Text(LsFM,width=37,height=10)
        self.EtrP.grid(column=1,row=2)
        LbS=Tk.Label(LsFM,text="startstate:",font=("Arial", 10),background="#EDE7E3")
        LbS.grid(column=0,row=3)
        self.EtrS=Tk.Entry(LsFM,width=50)
        self.EtrS.grid(column=1,row=3)
        LbG=Tk.Label(LsFM,text="Nama Machine:",font=("Arial", 10),background="#EDE7E3")
        LbG.grid(column=0,row=4)
        self.EtrG=Tk.Entry(LsFM,width=50)
        self.EtrG.grid(column=1,row=4)
    def openBaca(self):
        TBmac=Tk.Toplevel(self.mainwin)
        TBmac.geometry("800x600")
        Frame=Tk.Frame(TBmac,height=600,width=1000,background="#EDE7E3")
        Frame.place(relx=0.5,rely=0.5,anchor=Tk.CENTER)
        Frame.pack(fill="both",expand=True)
        Gframe=Tk.Frame(Frame,height=600,width=1000,background="#EDE7E3")
        Gframe.place(relx=0.5,rely=0.5,anchor=Tk.CENTER)
        Gframe.pack(expand=True)
        LBe=Tk.Label(Gframe,text="Nama machine:",font=("Arial", 10),background="#EDE7E3")
        LBe.grid(column=0,row=0)
        self.mcEtr=Tk.Entry(Gframe,width=50)
        self.mcEtr.grid(column=0,row=1)
        self.Btnbcmac=Tk.Button(Gframe,background="#82C0CC",text="Baca machine",width=20,height=2,command=self.readmachine,font=("Arial", 10,"bold"))
        self.Btncon=Tk.Button(Gframe,background="#82C0CC",text="convert",width=20,height=2,command=self.convertmch,font=("Arial", 10,"bold"))
        self.Btnsimp=Tk.Button(Gframe,background="#82C0CC",text="simplefikasi",width=20,height=2,command=self.simple,font=("Arial", 10,"bold"))
        self.Btnbcmac.grid(column=0,row=2)
        self.Btnsimp.grid(column=0,row=3)
        self.Btncon.grid(column=0,row=4)
    def getmachine(self):
        aT=self.EtrT.get()
        aV=self.EtrV.get()
        aP=self.EtrP.get("1.0",'end-1c')
        aS=self.EtrS.get()
        aG=self.EtrG.get()
        util.writemachine(aT,aV,aP,aS,aG)
    def readmachine(self):
        path = self.mcEtr.get()
        path=path+".txt"
        self.machine = CFGclass.CFGmsk(path)
    def convertmch(self):
        self.machine.convert()
    def simple(self):
        self.machine.simplfy()
    def openbckalimat(self):
        TBkal=Tk.Toplevel(self.mainwin)
        TBkal.geometry("800x600")
        Frame=Tk.Frame(TBkal,height=600,width=1000,background="#EDE7E3")
        Frame.place(relx=0.5,rely=0.5,anchor=Tk.CENTER)
        Frame.pack(fill="both",expand=True)
        Gframe=Tk.Frame(Frame,height=600,width=1000,background="#EDE7E3")
        Gframe.place(relx=0.5,rely=0.5,anchor=Tk.CENTER)
        Gframe.pack(expand=True)
        LBe=Tk.Label(Gframe,text="Kalimat:",font=("Arial", 10),background="#EDE7E3")
        LBe.grid(column=0,row=0)
        self.hsl=Tk.Label(Gframe,text="",font=("Arial", 10),background="#EDE7E3")
        self.hsl.grid(column=0,row=1)
        self.Kaletr=Tk.Entry(Gframe,width=50)
        self.Kaletr.grid(column=0,row=2)
        self.BtnKal=Tk.Button(Gframe,background="#82C0CC",text="Baca machine",width=20,height=2,command=self.cekkal,font=("Arial", 10,"bold"))
        self.BtnKal.grid(column=0,row=3)
    def cekkal(self):
        kalimatnya=self.Kaletr.get()
        self.hsl["text"]=self.machine.checkstring(kalimatnya)



top = Tk.Tk()
con=connection(top)
top.geometry("800x600")
Frame=Tk.Frame(top,height=600,width=300,background="#EDE7E3")
Frame.place(relx=0.5,rely=0.5,anchor=Tk.CENTER)
Frame.pack(fill="both",expand=True)
w=Tk.Label(Frame,text="Program Final Project Teori Bahasa dan Otomata",font=("Arial", 15,"bold"),background="#EDE7E3")
w.place(relx=.5,rely=.5,anchor=Tk.CENTER)
w.pack(expand=True)
ButtonFr=Tk.Frame(Frame,background="#EDE7E3")
ButtonFr.pack(anchor=Tk.N,expand=True)
ButtonTB=Tk.Button(ButtonFr,background="#82C0CC",text="Tambah bahasa",width=20,height=2,font=("Arial", 10,"bold"),command=con.openTBwindow)
ButtonTB.pack(anchor=Tk.N,expand=True)
ButtonBC=Tk.Button(ButtonFr,background="#82C0CC",text="Baca Bahasa",width=20,height=2,font=("Arial", 10,"bold"),command=con.openBaca)
ButtonBC.pack(anchor=Tk.N,expand=True)
ButtonCK=Tk.Button(ButtonFr,background="#82C0CC",text="Cek Kalimat",width=20,height=2,font=("Arial", 10,"bold"),command=con.openbckalimat)
ButtonCK.pack(anchor=Tk.N,expand=True)
top.mainloop()